### ISSUE TITLE
std::vector and qlat::vector resize problem

### ISSUE THREAD

**Issue by aroadant** [jinluchang/Qlattice#2]
https://github.com/waterret/Qlattice/blob/master/examples/cps-to-gwu/control_test_resize.cpp

The program will abort with "terminate called after throwing an instance of 'char const*'". Such a bug can be fixed by uncomment  line 6 of the cpp file. Not sure about where the problem.

Also, another test as the propS defined in line 43 with resize(1) in line 44 and then resize(5) in line 47. Even though the application works here, I found that the results will be incorrect in my other applications. I have to uncomment line 46 to reach the correct result. Unfortunately I don't have a clean and simple program to repeat the problem.

**Comment by jinluchang** [comment]
Issue fixed by adding move constructor to qlat::vector. The copy constructor of qlat::vector should be avoided in most cases.

**Comment by aroadant** [comment]
Luckily, I have repeated the prop resize without resize(0) problem in a simple case. The file https://github.com/waterret/Qlattice/blob/master/examples/cps-to-gwu/control_test_resize.cpp
has been updated. The output "Prop ori diff " will be nonzero in current case. The bug can also be fixed by uncomment line 64.

I will avoid resize without resize(0) if this is hard to solve.

**Comment by jinluchang** [comment]
Should be fixed with the lastest commit: https://github.com/waterret/Qlattice/commit/53e475f2db950e68f6d61cb924c75255f0dacb00

**Comment by aroadant** [comment]
It seems that current vector.h will have problem on GPU. The problematic code is updated in file https://github.com/waterret/Qlattice/blob/master/examples/cps-to-gwu/control_test_GPU_mem.cpp . The output will have error as follows. Whereas previous version https://github.com/waterret/Qlattice/blob/master/examples/cps-to-gwu/vector_Apr_ver.h will have no problem.

Timer::start                                           free_mem : 43.0%        4 calls 9.537E-07,2.371E-01 sec 17592.186 Gflops (1.678E+07 flops)
Timer::start                                     MemCache::gc() : 43.0%        4 calls 3.281E-01,2.371E-01 sec    3.273 Gflops (1.074E+09 flops)
qwarn: qassert: code == cudaSuccess from '/global/homes/g/genwang/project/genwang/Delta_mix/Code/Dec_29_2020/build//include/qutils/vector.h' line 77. (id_node=0 thread_num=0)
Timer::stack[  2]                                     MemCache::gc() : 43.028%        4 calls; 1.78E-01,7.11E-01 sec; 5.37E+08,2.15E+09 flops;  3.02 Gflops
Timer::stack[  1]                                           free_mem : 43.031%        4 calls; 1.78E-01,7.11E-01 sec; 5.41E+08,2.16E+09 flops;  3.04 Gflops
Timer::stack[  0]                                             Loop A :  0.000%        1 calls; 0.00E+00,0.00E+00 sec; 0.00E+00,0.00E+00 flops;  -nan Gflops
terminate called after throwing an instance of 'char const*'
[cgpu12:29915] *** Process received signal ***

**Comment by aroadant** [comment]
Correctly vector.h move construct.
